// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package usersdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetActiveUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetActiveUserByLogin(ctx context.Context, login string) (User, error)
}

var _ Querier = (*Queries)(nil)
