// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package usersdb

import (
	"context"

	"github.com/google/uuid"
)

const getActiveUserById = `-- name: GetActiveUserById :one
SELECT id, login, password_hash, created_at, disabled_at
FROM users
WHERE id = $1
  AND disabled_at IS NULL
`

func (q *Queries) GetActiveUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getActiveUserByLogin = `-- name: GetActiveUserByLogin :one
SELECT id, login, password_hash, created_at, disabled_at
FROM users
WHERE login = $1
  AND disabled_at IS NULL
`

func (q *Queries) GetActiveUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}
