// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package eventsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (event_id, occurred_at, source, type, level, actor_id, request_id, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (occurred_at, event_id) DO NOTHING
`

type CreateEventParams struct {
	EventID    uuid.UUID
	OccurredAt time.Time
	Source     string
	Type       string
	Level      int16
	ActorID    *string
	RequestID  *string
	Payload    []byte
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.EventID,
		arg.OccurredAt,
		arg.Source,
		arg.Type,
		arg.Level,
		arg.ActorID,
		arg.RequestID,
		arg.Payload,
	)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, event_id, occurred_at, received_at, source, type, level, actor_id, request_id, payload
FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.Source,
		&i.Type,
		&i.Level,
		&i.ActorID,
		&i.RequestID,
		&i.Payload,
	)
	return i, err
}
