// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventsdb

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	GetEventByID(ctx context.Context, id int64) (Event, error)
}

var _ Querier = (*Queries)(nil)
