// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sessionsdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	DeleteSessionByHash(ctx context.Context, tokenHash []byte) error
	DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error
	GetActiveSessionByHash(ctx context.Context, tokenHash []byte) (Session, error)
}

var _ Querier = (*Queries)(nil)
