// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package apikeysdb

import (
	"context"
)

const createApiKey = `-- name: CreateApiKey :exec
INSERT INTO api_keys (name, key_hash, source)
VALUES ($1, $2, $3)
`

type CreateApiKeyParams struct {
	Name    string
	KeyHash []byte
	Source  string
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) error {
	_, err := q.db.Exec(ctx, createApiKey, arg.Name, arg.KeyHash, arg.Source)
	return err
}

const getActiveApiKeyByHash = `-- name: GetActiveApiKeyByHash :one
SELECT id, name, key_hash, source, created_at, revoked_at
FROM api_keys
WHERE key_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) GetActiveApiKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Source,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
