// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package apikeysdb

import (
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID        uuid.UUID
	Name      string
	KeyHash   []byte
	Source    string
	CreatedAt time.Time
	RevokedAt *time.Time
}

type Event struct {
	ID         int64
	EventID    uuid.UUID
	OccurredAt time.Time
	ReceivedAt time.Time
	Source     string
	Type       string
	Level      int16
	ActorID    *string
	RequestID  *string
	Payload    []byte
}

type EventType struct {
	Type        string
	Description string
	Enabled     bool
}

type EventsDefault struct {
	ID         int64
	EventID    uuid.UUID
	OccurredAt time.Time
	ReceivedAt time.Time
	Source     string
	Type       string
	Level      int16
	ActorID    *string
	RequestID  *string
	Payload    []byte
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	CreatedAt    time.Time
	DisabledAt   *time.Time
}
