// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package apikeysdb

import (
	"context"
)

type Querier interface {
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) error
	GetActiveApiKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error)
}

var _ Querier = (*Queries)(nil)
