version: "2"
sql:
  - engine: postgresql
    schema: migrations
    queries: queries/apikeys
    gen:
      go:
        package: apikeysdb
        out: sqlcgen/apikeysdb
        sql_package: pgx/v5
        emit_interface: true
        emit_pointers_for_null_types: true
        overrides:
          - db_type: uuid
            go_type: github.com/google/uuid.UUID
          - db_type: timestamptz
            go_type: time.Time
          - db_type: timestamptz
            nullable: true
            go_type:
              import: time
              type: Time
              pointer: true
  # - engine: postgresql
  #   schema: migrations
  #   queries: queries/eventtypes
  #   gen:
  #     go:
  #       package: eventtypesdb
  #       out: sqlcgen/eventtypesdb
  #       sql_package: pgx/v5
  #       emit_interface: true
  #       emit_pointers_for_null_types: true
  - engine: postgresql
    schema: migrations
    queries: queries/users
    gen:
      go:
        package: usersdb
        out: sqlcgen/usersdb
        sql_package: pgx/v5
        emit_interface: true
        emit_pointers_for_null_types: true
        overrides:
          - db_type: uuid
            go_type: github.com/google/uuid.UUID
          - db_type: timestamptz
            go_type: time.Time
          - db_type: timestamptz
            nullable: true
            go_type:
              import: time
              type: Time
              pointer: true
  - engine: postgresql
    schema: migrations
    queries: queries/sessions
    gen:
      go:
        package: sessionsdb
        out: sqlcgen/sessionsdb
        sql_package: pgx/v5
        emit_interface: true
        emit_pointers_for_null_types: true
        overrides:
          - db_type: uuid
            go_type: github.com/google/uuid.UUID
          - db_type: timestamptz
            go_type: time.Time
          - db_type: timestamptz
            nullable: true
            go_type:
              import: time
              type: Time
              pointer: true
  - engine: postgresql
    schema: migrations
    queries: queries/events
    gen:
      go:
        package: eventsdb
        out: sqlcgen/eventsdb
        sql_package: pgx/v5
        emit_interface: true
        emit_pointers_for_null_types: true
        overrides:
          - db_type: uuid
            go_type: github.com/google/uuid.UUID
          - db_type: timestamptz
            go_type: time.Time
          - db_type: timestamptz
            nullable: true
            go_type:
              import: time
              type: Time
              pointer: true


